### ISSUE TITLE
Reduce rounding accuracy in statuses

### ISSUE THREAD

**Issue by amureki** [LambdaLint/lintipy#18]
Currently, it is very certain but looks alien, maybe it would be better to reduce it a bit:

![image](https://user-images.githubusercontent.com/627183/39014745-839de2a8-441b-11e8-91de-0d07e8b09136.png)

**Comment by codingjoe** [comment]
Good idea! I would go for 3 decimals (ms). what do you think?

**Comment by amureki** [comment]
@codingjoe apparently it is internal GitHub counter if I am not mistaken (we are providing `started_at` and `completed_at`, based on which it calculates time), so we cannot do anything here.
And looks like they fixed this:

![image](https://user-images.githubusercontent.com/627183/41000580-b6d43c4a-690e-11e8-9490-7cb18568b4c9.png)
